AgendaBundle\Entity\Contacto:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        apellido:
            type: string
            length: 255
        telefono:
            type: integer
    lifecycleCallbacks: {  }
