contacto:
    path:     /
    defaults: { _controller: "AgendaBundle:Contacto:index" }

contacto_show:
    path:     /{id}/show
    defaults: { _controller: "AgendaBundle:Contacto:show" }

contacto_new:
    path:     /new
    defaults: { _controller: "AgendaBundle:Contacto:new" }

contacto_create:
    path:     /create
    defaults: { _controller: "AgendaBundle:Contacto:create" }
    methods:  POST

contacto_edit:
    path:     /{id}/edit
    defaults: { _controller: "AgendaBundle:Contacto:edit" }

contacto_update:
    path:     /{id}/update
    defaults: { _controller: "AgendaBundle:Contacto:update" }
    methods:  [POST, PUT]

contacto_delete:
    path:     /{id}/delete
    defaults: { _controller: "AgendaBundle:Contacto:delete" }
    methods:  [POST, DELETE]
